layout_spectrum: 0.8364249
typography_spectrum: 0.8844857
color:
  saturation: 0.5379426
  lightness: 0.5008432
  brandStrength: 0.4907251
  brandColors:
    - '#FFFFFF'
    - '#1F1E0F'
    - '#E1E99A'
    - '#6E6E2F'
    - '#BDCF38'
  rhythmicContrast: 0.257167
name: Life LackaDaisiCal
